// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7gZiE1EpB5o1hJkmLmZ7yGSwOcdsc_tA',
    appId: '1:668248109606:web:9d48ca234c63ec4e6bace7',
    messagingSenderId: '668248109606',
    projectId: 'tjibarusa',
    authDomain: 'tjibarusa.firebaseapp.com',
    storageBucket: 'tjibarusa.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBEgLQCN6KY1jS4v02P14nsYPDewfy_UBs',
    appId: '1:668248109606:android:d3bb2ee3e8f47cd26bace7',
    messagingSenderId: '668248109606',
    projectId: 'tjibarusa',
    storageBucket: 'tjibarusa.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB7gZiE1EpB5o1hJkmLmZ7yGSwOcdsc_tA',
    appId: '1:668248109606:web:6eb9bc72329676f66bace7',
    messagingSenderId: '668248109606',
    projectId: 'tjibarusa',
    authDomain: 'tjibarusa.firebaseapp.com',
    storageBucket: 'tjibarusa.firebasestorage.app',
  );
}
